# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  containerapp-name: order-tracking
  resourcegroup-name: networking_resource_group
  dockerusername: karlosmoodios
  imagename: order-tracking
  environment-name: ordertracking-env
  
steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'spn-docker-hub-registry'
    repository: 'karlosmoodios/order-tracking'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'spn-04-29-23-azure-cxp'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az config set extension.use_dynamic_install=yes_without_prompt
      
      az containerapp up -n $(order-tracking) -g $(networking_resource_group) --image karlosmoodios)/order-tracking:latest --environment order-tracking-env --ingress external --target-port 80 --registry-username karlosmoodios --registry-password dckr_pat__HRRGpIOgvuSXc98BbR2taRVoYI --registry-server hub.docker.com --query properties.configuration.ingress.fqdn

